working_dir: '/data/swamyvs/ocular_transcriptomes_paper/'
data_dir: '/data/swamyvs/ocular_transcriptomes_pipeline/old_data/'
longread_dir: '/data/swamyvs/pacbio_testing/'
sample_file: '/data/swamyvs/ocular_transcriptomes_pipeline/sampleTableFullV3.tsv'
salmon_version: 'salmon/1.1.0'
R_version: 'R/3.5.0'
bedtools_version: 'bedtools/2.27.1'
fastq_path: '/data/OGVFB_BG/EiaD_2019_05/'
TransDecoder_version: 'TransDecoder/5.0.1'
subtissue_file: '/data/swamyvs/ocular_transcriptomes_pipeline/ref/subtissues.txt'
files_yaml: /data/swamyvs/ocular_transcriptomes_paper/files.yaml
